import spacy
from pathlib import Path

from nltk import pos_tag
from openai import OpenAI

from gensim import downloader as api

from collections import defaultdict

from src import utils
from src.homophone_gen import HomophoneGenerator


class PunGenerator:

    def __init__(self, homophone_df_path: Path, load_homophone: bool=False):
        
        self.top_n_context_thresh = 5
        self.spacy_en = spacy.load("en_core_web_sm")

        # Load pre-trained Word2Vec model
        self.embedding_model = api.load("glove-twitter-200")
        self.embedding_vocab : set = set(self.embedding_model.index_to_key)
        
        if load_homophone is True:
            # If homophones have already been generated, load the file 
            self.homophone_gen = HomophoneGenerator(load_df_file=homophone_df_path)
        else:
            # Create the homophone df from scratch
            self.homophone_gen = HomophoneGenerator(save_df_file=homophone_df_path)
            self.homophone_gen.get_homophones_df()
            self.get_sentences_per_en()
            self.save_homophone_df()

        self.llm_client = OpenAI()
        self.pun_list = []

    def replace_noun_phrase(self, input_sentence, word_context_change, word_en, word_replace):
        # Get the spacy text object for the input sentence
        text_obj = self.spacy_en(input_sentence)

        # Replace the english word with the transliterated hindi word
        # Possible to improve this function a bit
        input_sentence = input_sentence.replace(word_en, word_replace)

        # Extract noun phrases
        noun_phrases = [n.text for n in text_obj.noun_chunks]
        if len(noun_phrases) == []:
            return

        similar_words = []
        # Check if input word is in the vocabulary
        if word_context_change in self.embedding_vocab:
            # Get most similar words
            similar_words = self.embedding_model.most_similar(word_context_change, topn=self.top_n_context_thresh)

            # Return the first similar word
            for reqd_word, _ in similar_words:
                if utils.is_noun(reqd_word):
                    # Replace the first noun phrase in the input sentence
                    new_sentence = input_sentence.replace(noun_phrases[0], reqd_word, 1)

                    # Add the generated sentence to the pun list
                    self.pun_list.append(new_sentence)

    
    def get_pun_from_translated_context(self):

        for _, row in self.homophone_gen.homophone_df.iterrows():
            # For all the sentences where the row 'en' word appears at the end, try to create puns
            # by replace the noun at the start with a potential context word of the associated homophone word
            for input_sentence in row.candidate_sentences:
                self.replace_noun_phrase(input_sentence, row.translated_hi_en, row.en, row.latin_hi)

    def clean_llm_results():
        pass

    def prompting_llm(self, method='fewshot'):
        if method == 'zeroshot':
            prompt_folder = Path('prompts/zeroshot')
        elif method == 'oneshot':
            prompt_folder = Path('prompts/oneshot')
        else:
            prompt_folder = Path('prompts/fewshot')
        
        prompt_instruct_folder = prompt_folder / 'input'
        prompt_result_folder = prompt_folder / 'results'
        
        for f in prompt_instruct_folder.iterdir():
            # Read the prompt to be given to the LLM
            message_prompt = utils.read_file(f) 
            # Call the LLM Api to get the required response
            # Temperature is high, since we want more deterministic outputs
            response = self.llm_client.chat.completions.create(
                messages=[
                        {
                            "role": "user",
                            "content": message_prompt
                        }
                ],
                model="gpt-3.5-turbo",
                temperature=0.3,
                n=1,
            )
            # Retrieve the prompt result from the LLM
            response = response.choices[0].text.strip()

            # Remove the extra details and just keep the pun
            required_pun = utils.post_process_llm_response(response)
            # Add the generated pun to the list of puns generated by the system
            self.pun_list.append(required_pun)

            result_file = prompt_result_folder / f.name
            
            if result_file.exists():
                # Append the new prompt result to the result file
                existing_data = utils.read_file(result_file)
                response = existing_data + '\n' + response

            # Write the raw response received from the LLM to the result files
            utils.write_file(response, result_file)
            

                
